[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor
    enjoyneering/HTU21D
    bblanchon/ArduinoJson
